[[main]]
  name = "Writing"
  pageRef = "posts"
  weight = 10
[[main]]
  name = "Work"
  pageRef = "work"
  weight = 20
[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 25

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30
